matter-labs/era-compiler-tester

benchmark_analyzer/src/benchmark_analyzer/arguments.rs
benchmark_analyzer/src/benchmark_analyzer/main.rs

The maximal size of an individual group displayed by benchmark analyzer is not fixed to 100 now but can be passed through CLI. 
Easier than remove too many examples in each category manually or via a script.

feature: benchmark-analyzer accepts max group size

---

Cargo.lock
compiler_tester/src/lib.rs

**Merging this PR requires merging https://github.com/matter-labs/era-compiler-llvm-context/pull/24 first.**
Support creating subfolders in `debug/`.
Compiler tester overrides IR dumps if they were produced by launching a test repeatedly with different modes.
This change should not break behavior expected from `era-compiler-llvm-context`.
Initially I wanted to just encode modes in the filenames but it turned out to be very intrusive to the code base (for one, dumping `.yul` files is done by a very different code than dumping everything else). Therefore we are creating a subdirectory per mode.

feat: create a subdirectory per mode in debug/

---

compiler_tester/src/compiler_tester/arguments.rs
compiler_tester/src/compiler_tester/main.rs
compiler_tester/src/lib.rs
compiler_tester/src/workflow.rs
fuzzer/fuzz_targets/common.rs

Compiler tester may now build tests without running them. This is useful to dump IRs quickly. 
The CLI interface did not change but now accepts an optional `--workflow=[run|build]` argument, `run` being default.

feat: compiling tests without executing them

---

.github/actions/build-llvm/action.yml
.github/workflows/benchmarks.yml
.github/workflows/tests.yaml

Use the new LLVM builder with --target-env option + small CI fixes.
To get the latest builder from cargo, facilitate its updates in the future, and simplify CI.

ci: update llvm builder

---

benchmark_analyzer/src/benchmark/group/results.rs
benchmark_analyzer/src/benchmark/mod.rs
compiler_tester/src/directories/matter_labs/test/metadata/evm_contract.rs
compiler_tester/src/directories/matter_labs/test/mod.rs

This PR adds the code necessary to perform the tests of the rest of the opcodes added on this [PR](https://github.com/matter-labs/era-compiler-tests/pull/29)
The Before case for the tests was added because when you tried to write a test that needed to create a contract, since the Template and Full share the vm instance, they both created the same contract, so the decommiter failed since it already knew the hash, that's why the Before test was added, in order to run the contract creation in it before Template and Full, so that the gas comparisons were still correct (instead of creating the contract on Template and not in Full, since that way a specific opcode gas would not be tested)

feat: tests for remaining EVM opcodes

---

Cargo.lock
compiler_tester/Cargo.toml
compiler_tester/src/compilers/solidity/mod.rs
compiler_tester/src/compilers/yul/mod.rs
fuzzer/Cargo.toml

1. Optimizes the RAM usage while running recursive child processes of itself.
2. Includes an LLVM fix for the GVN/NewGVN optimizer pass.
The RAM usage with large projects was over the top and caused OOM.

fix: optimize RAM usage in zksolc and zkvyper

---

.gitmodules
Cargo.lock
README.md
compiler_tester/Cargo.toml
compiler_tester/src/compilers/mode/mod.rs
compiler_tester/src/compilers/solidity/mode.rs
compiler_tester/src/compilers/solidity/upstream/mode.rs
compiler_tester/src/lib.rs
fuzzer/Cargo.toml

1. Renames the `y` mode to `I`.
2. Renames the `zkevm` folder to `eravm`.
1. It conflicts with `Y` when dumping the debug output, because folder names cannot be case-sensitive.
2. The old name is obsolete.

chore: zkevm -> eravm, y -> I

---

.github/workflows/benchmarks.yml
.github/workflows/ccache-regen.yml
.github/workflows/tests.yaml

Test workflow is [here](https://github.com/matter-labs/era-compiler-tester/actions/runs/9467920030).
Additional checkout was required for `LLVM.lock`.

ci: fix ccache regeneration workflow

---

.github/workflows/sanitizers.yml

Add manual workflow to run `compiler-tester` with sanitizers enabled.
The workflow is working as follows:
1. Build LLVM with sanitizer specified with `llvm-sanitizer` parameter
2. Build FE compilers with sanitizer specified with `rust-sanitizer` parameter
3. Build compiler-tester itself with sanitizer specified with `rust-sanitizer` parameter
More info about Rust sanitizers is available [here](https://rustc-dev-guide.rust-lang.org/sanitizers.html).
Possible values are: `address`, `cfi`, `hwaddress`, `kcfi`, `leak`, `memory`, or `thread`
Only `memory` and `thread` were tested and supported for now, although CI allows us to try other variations.
For more information about the supported sanitizers in LLVM, see [this page](https://www.llvm.org/docs/CMake.html#:~:text=the%20LLVM_SOURCE_PREFIX%2 …

ci: support workflow with sanitizers

---

.gitmodules
Cargo.lock
compiler_tester/Cargo.toml
compiler_tester/src/compilers/solidity/mod.rs
compiler_tester/src/directories/ethereum/test.rs
compiler_tester/src/directories/matter_labs/test/mod.rs
fuzzer/Cargo.toml

1. Removed obsolete warnings for `ecrecover` and `extcodesize`.
2. `send`/`transfer` now trigger an error with ZKsync edition of solc.
3. Added the `suppress-errors` parameter to suppress the error above.

feat: remove obsolete warnings

---

configs/vyper-bin-default.json

Add Linux arm64 platform dir for vyper binaries.
To be able to run compiler tester on Linux ARM64 without issues.

chore: add linux arm64 platform dir for vyper bins

---

.gitmodules
Cargo.lock

1. Fixes some obsolete Solidity tests metadata.
2. Unignores the last ignored test `split.vy`.
3. Removes Ethereum artifacts from rewritten Vyper tests.

fix: remove redundant Ethereum artifacts from Vyper tests

---

.github/workflows/benchmarks.yml

Before, by mistake `main` was cloned for LLVM even if LLVM.lock was different.

ci: fix default llvm versions for benchmarks

---

fuzzer/README.md
fuzzer/fuzz_targets/common.rs
fuzzer/fuzz_targets/demo.rs
fuzzer/fuzz_targets/optimizer_bug.rs

Fix readme and targets after renaming `fuzz` to `fuzzer` on the top level.

fuzzer: fix readme and targets after renaming

---

compiler_tester/src/vm/eravm/system_context.rs

After some refactors on the system context storage a wrong address was used instead of the one for the `ecrecover`.
This change is needed for one of the semanticTest (`solidity/test/libsolidity/semanticTests/various/codebalance_assembly.sol`) to pass.

fix: upstream balance for `ecrecover` address

---

.gitmodules
Cargo.lock
compiler_tester/Cargo.toml

Burn all gas with assert unreachable.
Fixes https://github.com/matter-labs/era-compiler-vyper/issues/83
It has been translated to the equivalent of `REVERT` instead of `INVALID`.

fix: burn all gas with assert unreachable

---

Cargo.lock
compiler_tester/Cargo.toml
compiler_tester/src/compilers/vyper/mod.rs
compiler_tester/src/vm/eravm/mod.rs

Removes all calls to `vyper` except `batch`. Now all data will be requested with a single call to `batch`, as it is the most universal endpoint of the underlying `vyper` compiler. 
At the moment (v0.4.0) it is extremely slow and single-threaded. It takes eternity to run on MacOS arm64, probably due to compatibility reasons.

feat: vyper combined JSON I/O overhaul

---

compiler_tester/src/test/case/mod.rs
compiler_tester/src/vm/eravm/mod.rs
compiler_tester/src/vm/eravm/system_context.rs

This PR makes the EVM tests increase their block number and timestamp for every transaction of a test input (in ZKSync Era this task is usually done by the bootloader, but there's no bootloader here). This fixes all the `semanticTests` related to either block hashes or block timestamps.

fix: make EVM tests have increasing block numbers and timestamps

---

compiler_tester/src/test/case/input/output/event.rs
compiler_tester/src/vm/eravm/mod.rs
compiler_tester/src/vm/evm/mod.rs
compiler_tester/src/vm/evm/runtime.rs
solidity_adapter/src/test/function_call/parser/lexical/stream/integer/mod.rs
solidity_adapter/src/test/function_call/parser/lexical/stream/word/mod.rs

Clippy auto-fixes for some (not all) warnings which were annoying me as I learn Rust, via
```
__CARGO_FIX_YOLO=1  cargo clippy --fix --allow-dirty  -- -Dwarnings
```

`clippy --fix`s

---

.github/workflows/sanitizers.yml

Add the capability to choose the LLVM branch when running with sanitizers.
To allow testing different LLVM branches without the need to create a branch and update `LLVM.lock` manually.
Tested manually through actions:
1. [Run with a custom branch](https://github.com/matter-labs/era-compiler-tester/actions/runs/10522529132/job/29155353431)
2. [Run with a default '' empty value](https://github.com/matter-labs/era-compiler-tester/actions/runs/10522603413)

ci: support custom LLVM branch in sanitizers

---

compiler_tester/src/vm/eravm/mod.rs

Required for https://github.com/matter-labs/era-contracts/pull/738
The logic of prepopulating **storage** is left for compatibility with the previous version of the contract

feat: Prepopulate tstorage for the new version of EvmGasManager

---

.github/workflows/tests.yaml

Returns `v1` stable tag for CI benchmarks job.
To stabilize CI.

ci: update benchmarks back to stable tag

---

.github/workflows/sanitizers.yml

Introduce `--target` parameter in the sanitizer workflow.
`--target` parameter is mandatory now.

ci: add mandatory target parameter to sanitizers workflow

---

.github/workflows/sanitizers.yml

Fix sanitizers mode to 0.8.27 after solc update.

ci: fix sanitizers mode to 0.8.27 after solc update

---

Cargo.lock
Cargo.toml
benchmark_analyzer/Cargo.toml
benchmark_analyzer/src/benchmark_analyzer/arguments.rs
benchmark_analyzer/src/benchmark_analyzer/main.rs
compiler_tester/Cargo.toml
compiler_tester/src/compiler_tester/arguments.rs
compiler_tester/src/compiler_tester/main.rs
compiler_tester/src/compilers/solidity/mod.rs
compiler_tester/src/compilers/yul/mod.rs
compiler_tester/src/workflow.rs
coverage_watcher/Cargo.toml
coverage_watcher/src/coverage_watcher/arguments.rs
coverage_watcher/src/coverage_watcher/main.rs
deny.toml
rust-toolchain.toml
solidity_adapter/Cargo.toml
solidity_adapter/src/tests_updater/arguments.rs
solidity_adapter/src/tests_updater/main.rs

Fixes the EVMLA pipeline for EVM target.
Some deploy code functions were unsupported.

feat(evm): EVMLA (E, I) pipelines

---

Cargo.lock
compiler_tester/Cargo.toml
compiler_tester/src/benchmark_format.rs
compiler_tester/src/compiler_tester/arguments.rs
compiler_tester/src/compiler_tester/main.rs
compiler_tester/src/compilers/vyper/mod.rs
compiler_tester/src/lib.rs
solidity_adapter/Cargo.toml

Tests the v1.5.8 release build.

release: v1.5.8

---

README.md
compiler_tester/src/compilers/mode/imode.rs
compiler_tester/src/compilers/mode/mod.rs
compiler_tester/src/filters.rs

After the massive refactoring mode filters were broken.
Now not only they are repaired (so that they work as they did previously) but they are space-insensitive.
Mode filters such `Y+M3B3` and `Y +  M3 B3     0.1.2` are now equivalent.

Fix mode filters

---

benchmark_analyzer/src/analysis/mod.rs

Makes EVM interpreter reports concise again.

fix: make EVM interpreter reports concise again

---

.github/workflows/tests.yaml
benchmark_analyzer/src/model/benchmark/test/codegen/versioned/executable/run/mod.rs
benchmark_analyzer/src/model/context/mod.rs
benchmark_analyzer/src/output/format/json/lnt/benchmark/machine.rs
benchmark_analyzer/src/output/format/json/lnt/benchmark/mod.rs
benchmark_analyzer/src/output/format/json/lnt/benchmark/run_description.rs
benchmark_analyzer/src/output/format/json/lnt/mod.rs
benchmark_analyzer/src/util/mod.rs

Serialization and LNT report fixes for proper reports uploading to the LNT server.

fix: LNT report serialization updates

---

benchmark_analyzer/src/analysis/mod.rs
benchmark_analyzer/src/results/mod.rs

1. Filters out the `I` codegen.
2. Brings back the narrow report formatting.
1. It is not exposed to users, and was added only to get more test inputs.
2. The new format is too wide for mobile devices.

fix: filter out the I codegen

---

.gitmodules
Cargo.lock
compiler_tester/Cargo.toml
configs/vyper-bin-default.json

- Add vyper bin default config for vyper 0.4.1
Tests are all running. But there are warnings for deprecated functions `>= 0.4.0`:
- `shift` -> use `<<` or `>>`
- `log`: `Deprecation: Instantiating events with positional arguments is deprecated as of v0.4.1 and will be disallowed in a future release. Use kwargs instead`
*Related issue:* https://github.com/matter-labs/era-compiler-vyper/issues/156
*Related PR for `era-compiler-vyper`:* https://github.com/matter-labs/era-compiler-vyper/pull/157
Needed branch to test in `compiler_tester/Cargo.toml`:
```toml
era-compiler-vyper = { git = "https://github.com/s3bc40/era-compiler-vyper", branch = "feat/add-support-vyper-0-4-1" }
```
To allow `era-compiler-tester` to run with `vyper==0.4.1`. 
Previous tests are already adapted with `#! { "modes": [ …

feat: Add support for vyper 0.4.1

---

Cargo.lock
LLVM.lock

Sets the LLVM branch back to main after the LLVM update.

chore: set the LLVM branch back to main

---

.github/workflows/ccache-regen.yml
.github/workflows/sanitizers.yml
.github/workflows/scheduled.yaml
.github/workflows/tests.yaml
.gitignore
.gitmodules
LLVM.lock

To simplify setup without the need of `zksync-llvm` to clone LLVM.

chore: support llvm as a git submodule
