matter-labs/era-compiler-tester

.github/actions/build-llvm/action.yml
.github/workflows/benchmarks.yml
fuzz/Cargo.toml

1. Use the latest llvm builder
2. Fix cargo fuzz license
Small CI enhancements.

ci: use the most recent llvm builder

---

.github/actions/build-llvm/action.yml
CONTRIBUTING.md
README.md
compiler_tester/src/vm/eravm/system_context.rs

Fixes README.md after LLVM 17 and builder updates:
To fix documentation issues.

docs: update setup and build instructions

---

Cargo.lock
README.md
benchmark_analyzer/Cargo.toml
benchmark_analyzer/src/benchmark/group/results.rs
compiler_tester/Cargo.toml
compiler_tester/src/compilers/llvm/mod.rs
compiler_tester/src/compilers/solidity/mod.rs
compiler_tester/src/compilers/yul/mod.rs
compiler_tester/src/directories/matter_labs/test/metadata/evm_contract.rs
compiler_tester/src/directories/matter_labs/test/mod.rs
coverage_watcher/Cargo.toml
fuzzer/Cargo.toml
solidity_adapter/Cargo.toml

Updates the interfaces for Yul projects with multiple files.
The support was added to `zksolc`.

feat: support Yul projects with multiple files

---

Cargo.lock
compiler_tester/src/compilers/llvm/mod.rs
compiler_tester/src/compilers/solidity/mod.rs
compiler_tester/src/compilers/solidity/upstream/mod.rs
compiler_tester/src/compilers/vyper/mod.rs
compiler_tester/src/compilers/yul/mod.rs

Updates deps after a major revamp of the zksolc interface.

chore: update interfaces after solc revamp

---

.github/workflows/tests.yaml

Add advanced cargo checks: fmt, clippy, udeps (unused dependencies), audit
[Testing workflow](https://github.com/matter-labs/era-compiler-tester/actions/runs/9613584351/job/26516615188?pr=52)

ci: add advanced cargo checks including fmt, clippy, and audit

---

.gitmodules
Cargo.lock
compiler_tester/Cargo.toml
compiler_tester/src/compilers/solidity/mod.rs
compiler_tester/src/compilers/vyper/mod.rs
configs/vyper-bin-default.json

Support for vyper 0.4.0.
It has been released by the Vyper team recently.

feat: support vyper v0.4.0

---

fuzzer/README.md
fuzzer/fuzz_targets/common.rs
fuzzer/fuzz_targets/demo.rs
fuzzer/fuzz_targets/optimizer_bug.rs

Update ReadMe to reflect demo name.
[skip actions]

fuzzer: fix readme and targets after renaming; simple ⇒ demo

---

.gitmodules
Cargo.lock
compiler_tester/Cargo.toml

Fixes the ignored loop range bounds.

fix: ignored loop range bounds

---

compiler_tester/src/vm/eravm/mod.rs

fix: increase EVM calls gas limit

---

.github/workflows/sanitizers.yml

To be able to run sanitizers workflows manually when required.

ci: update sanitizers workflow

---

.github/workflows/ccache-regen.yml
.github/workflows/sanitizers.yml
.github/workflows/tests.yaml
solidity_adapter/src/index/test_file.rs
solidity_adapter/src/test/mod.rs

Update:
Minor fixes:
To be able to test all targets dynamically.
No labels, default target (no --target parameter):
EraVM target only:
EVM target only:
Both targets generated:

ci: support eravm and evm execution targets

---

compiler_tester/src/test/case/input/value.rs
compiler_tester/src/vm/eravm/mod.rs
compiler_tester/src/vm/eravm/system_context.rs

Fixes tests for block hash.
They were broken after merging the EVM target.

fix: block hash

---

Cargo.lock

Adds a test for AAVE misoptimization bug.
The bug has been fixed, and all contracts have been proved to be unaffected.

fix: the AAVE misoptimization bug

---

Cargo.lock
compiler_tester/src/test/case/input/balance.rs
compiler_tester/src/vm/revm/balance.rs

Tests the CI with era-compiler-solidity workspace.

test: era-compiler-solidity workspace

---

.github/workflows/ccache-regen.yml
.github/workflows/sanitizers.yml
.github/workflows/tests.yaml

ci: update runner labels to high performance

---

Cargo.lock

release: zksolc v1.5.4

---

.gitmodules
compiler_tester/src/vm/eravm/mod.rs

chore: Update contracts and adapt for new EvmGasManager layout

---

.github/workflows/sanitizers.yml
.gitmodules
Cargo.lock
compiler_tester/Cargo.toml
compiler_tester/src/compiler_tester/main.rs
compiler_tester/src/test/case/input/balance.rs
compiler_tester/src/test/case/input/deploy_eravm.rs
compiler_tester/src/test/case/input/deploy_evm.rs
compiler_tester/src/test/case/input/mod.rs
compiler_tester/src/test/case/input/runtime.rs
compiler_tester/src/test/case/mod.rs
configs/solc-bin-default.json
configs/solc-bin-upstream.json
ethereum.yaml
fuzzer/Cargo.toml

Tests the support for solc v0.8.28.

feat: test solc v0.8.28

---

Cargo.lock
compiler_tester/Cargo.toml

1. Memcpy declaration pointer order.
2. Event intrinsics argument order.

fix(evm): memcpy and event intrinsic argument order

---

Cargo.lock
benchmark_analyzer/Cargo.toml
compiler_tester/Cargo.toml
coverage_watcher/Cargo.toml
fuzzer/Cargo.toml
solidity_adapter/Cargo.toml

release: v1.5.5

---

compiler_tester/src/vm/eravm/system_contracts.rs

chore: Update contracts

---

deny.toml

Update cargo deny config.
New license for Unicode and some updates for new version.

ci: update cargo deny config

---

.github/workflows/secrets-scanner.yaml
.github/workflows/tests.yaml

Fix mandatory CI checks.
To properly add in terraform.

ci: fix mandatory checks to be included in terraform

---

Cargo.lock
benchmark_analyzer/src/util/btreemap.rs
compiler_tester/src/compilers/eravm/mod.rs
compiler_tester/src/compilers/llvm/mod.rs
compiler_tester/src/compilers/solidity/mod.rs
compiler_tester/src/compilers/vyper/mod.rs
compiler_tester/src/compilers/yul/mod.rs

Tests the release of zksolc and zkvyper v1.5.9.

release: v1.5.9

---

.github/workflows/ccache-regen.yml
.github/workflows/tests.yaml
Cargo.lock
compiler_tester/Cargo.toml

To fix and stabilize testing workflows.

ci: fix evm benchmarks and add proper ccache regen

---

.github/workflows/sanitizers.yml

Add toolchain and environment parameters to sanitizers tests.

ci: add toolchain and environment parameters to sanitizers tests

---

.github/workflows/scheduled.yaml

chore: fix macos runner

---

Cargo.lock

Adds support for bytecode metadata.

feat(evm): add the EVM metadata

---

Cargo.lock
benchmark_analyzer/src/benchmark_converter/tests.rs
benchmark_analyzer/src/util/btreemap.rs
configs/solc-bin-default.json
configs/solc-bin-system-contracts.json
solidity_adapter/src/test/function_call/parser/lexical/stream/integer/mod.rs
solidity_adapter/src/test/function_call/parser/lexical/stream/word/mod.rs

Bumps solc revision to v1.0.2.
It has just been released.

chore: bump solc revision to v1.0.2

---

.gitmodules
Cargo.lock
compiler_tester/Cargo.toml
compiler_tester/src/compiler_tester/main.rs
configs/solc-bin-default.json
configs/solc-bin-upstream.json
ethereum.yaml
solidity_adapter/src/tests_updater/arguments.rs

feat: support solc v0.8.30

---

Cargo.lock
compiler_tester/src/compilers/llvm_ir/mod.rs
compiler_tester/src/compilers/solidity/solx/mod.rs
compiler_tester/src/compilers/solidity/zksolc/mod.rs
compiler_tester/src/compilers/yul/mod.rs
configs/solc-bin-default.json

Updates interfaces after https://github.com/matter-labs/solx/pull/65

feat: strict selection of standard JSON output data

---

Cargo.lock
compiler_tester/src/compilers/solidity/solx/mod.rs

Runs tests on solx v0.1.0-alpha.4.

chore: test solx v0.1.0-alpha.4

---

benchmark_analyzer/src/analysis/mod.rs
benchmark_analyzer/src/benchmark_analyzer/main.rs
benchmark_analyzer/src/results/mod.rs

Replaces float number comparisons with integer ones. Fixes some variable names.

fix: a couple of variable names and conditions

---

.gitmodules
Cargo.lock
compiler_tester/Cargo.toml
compiler_tester/src/compilers/llvm_ir/mod.rs
compiler_tester/src/compilers/solidity/solx/mod.rs
compiler_tester/src/compilers/yul/mod.rs

Tests https://github.com/matter-labs/solx/pull/106

feat(evm): move the spill area handling to solx

---

Cargo.lock

Tests https://github.com/matter-labs/solx/pull/114

feat(evm): support pipeline profiling

---

Cargo.lock

Tests https://github.com/matter-labs/solx/pull/116

feat(evm): add an LLVM attribute for EVM entry functions

---

.github/workflows/scheduled.yaml

Outdated windows and macos ones.

chore: fix scheduled workflow runners

---

Cargo.lock
compiler_tester/src/compilers/llvm_ir/mod.rs
compiler_tester/src/compilers/solidity/cache_key.rs
compiler_tester/src/compilers/solidity/solc/compiler/standard_json/input/mod.rs
compiler_tester/src/compilers/solidity/solc/compiler/standard_json/input/settings/mod.rs
compiler_tester/src/compilers/solidity/solc/compiler/standard_json/input/settings/optimizer/mod.rs
compiler_tester/src/compilers/solidity/solc/compiler/standard_json/input/settings/selection/file/mod.rs
compiler_tester/src/compilers/solidity/solc/compiler/standard_json/input/settings/selection/mod.rs
compiler_tester/src/compilers/solidity/solc/mod.rs
compiler_tester/src/compilers/solidity/solx/mod.rs
compiler_tester/src/compilers/solidity/solx/mode.rs
compiler_tester/src/compilers/solidity/zksolc/mod.rs
compiler_tester/src/compilers/yul/mod.rs
configs/solc-bin-llvm.json

feat(evm): update the MLIR integration to solc-0.8.30
